# Site settings
title: Financial forecast
email: financial@consider-it.de
url: https://l4cast.github.io/financial-forecast/
description: "AI based financial liquidity forecast."

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Financial forecast

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Imprint
    url: https://www.consider-it.de/impressum
#  - title: facebook#
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/tlwt

# Build settings
markdown: kramdown
permalink: pretty
